# Generated by Django 4.2.16 on 2024-10-20 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exceeded_at", models.DateTimeField(blank=True, null=True)),
                ("limit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("performed_at", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance_app.categorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringTransactionModel",
            fields=[
                (
                    "transactionmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finance_app.transactionmodel",
                    ),
                ),
                ("interval_seconds", models.PositiveIntegerField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("finance_app.transactionmodel",),
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "global_notification_mode",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("APP", "App"),
                            ("EMAIL", "Email"),
                            ("APP_EMAIL", "App and Email"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_app.userprofilemodel",
            ),
        ),
        migrations.CreateModel(
            name="SharedBudgetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("VIEW", "View"), ("EDIT", "Edit")],
                        default="VIEW",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT", "Participant"),
                            ("OBSERVER", "Observer"),
                        ],
                        default="PARTICIPANT",
                        max_length=12,
                    ),
                ),
                ("on_exceeded", models.BooleanField(default=True)),
                ("on_limit_change", models.BooleanField(default=True)),
                ("on_transaction", models.BooleanField(default=True)),
                (
                    "notification_mode",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("APP", "App"),
                            ("EMAIL", "Email"),
                            ("APP_EMAIL", "App and Email"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.budgetmodel",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.userprofilemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryPreferenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=7)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.categorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_app.userprofilemodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="users",
            field=models.ManyToManyField(blank=True, to="finance_app.userprofilemodel"),
        ),
        migrations.AddField(
            model_name="budgetmodel",
            name="categories",
            field=models.ManyToManyField(blank=True, to="finance_app.categorymodel"),
        ),
        migrations.AddField(
            model_name="budgetmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_app.userprofilemodel",
            ),
        ),
    ]
