# Generated by Django 4.2.16 on 2024-10-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="_user",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
