# Generated by Django 4.2.16 on 2024-10-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0002_rename_user_userprofile__user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="_user",
            new_name="user",
        ),
    ]
