# Generated by Django 4.2.16 on 2024-10-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_app", "0003_rename__user_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="users",
        ),
    ]
