name: DJlint

on: [push, pull_request]

permissions:
  contents: write  # Allow actions to push changes to the repository

jobs:
  lintAndReformat:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for proper commits

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Reformat with DJlint
      run: |
        . venv/bin/activate
        djlint . --reformat || true

    - name: Commit reformatted code
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Apply DJlint reformatting" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref }}  # Push changes to the same branch

    - name: Lint with DJlint
      run: |
        . venv/bin/activate
        djlint . --lint
